### ISSUE TITLE
Unable to proceed past the setup page

### ISSUE THREAD

**Issue by micruzz82** [mistergates/ipmon#6]
Hi.. thank you for your app. I was trying to use it but once I fill the form the app crashes.

I've put the stack trace below. Would you be able to advise what I need to do to get the app working please?

10.23.159.115 - - [20/Mar/2021 19:31:28] "GET / HTTP/1.1" 302 -
10.23.159.115 - - [20/Mar/2021 19:31:28] "GET /setup HTTP/1.1" 200 -
2021-03-20 19:31:59,734 INFO sqlalchemy.engine.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS "'test plain returns'"
2021-03-20 19:31:59,734 INFO sqlalchemy.engine.Engine ()
2021-03-20 19:31:59,735 INFO sqlalchemy.engine.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS "'test unicode returns'"
2021-03-20 19:31:59,735 INFO sqlalchemy.engine.Engine ()
2021-03-20 19:31:59,737 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-03-20 19:31:59,737 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("users")
2021-03-20 19:31:59,738 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,738 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("users")
2021-03-20 19:31:59,738 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,739 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("pollHistory")
2021-03-20 19:31:59,739 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,739 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("pollHistory")
2021-03-20 19:31:59,739 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,739 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("hostAlerts")
2021-03-20 19:31:59,740 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,740 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("hostAlerts")
2021-03-20 19:31:59,740 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,740 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("smtp")
2021-03-20 19:31:59,740 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,741 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("smtp")
2021-03-20 19:31:59,741 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,741 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("hosts")
2021-03-20 19:31:59,741 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,741 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("hosts")
2021-03-20 19:31:59,742 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,742 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("polling")
2021-03-20 19:31:59,742 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,742 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("polling")
2021-03-20 19:31:59,743 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,743 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("web_themes")
2021-03-20 19:31:59,743 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,743 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("web_themes")
2021-03-20 19:31:59,743 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-20 19:31:59,745 INFO sqlalchemy.engine.Engine 
CREATE TABLE users (
        id INTEGER NOT NULL, 
        username VARCHAR(20) NOT NULL, 
        email VARCHAR(50) NOT NULL, 
        password VARCHAR(200) NOT NULL, 
        date_created DATE, 
        alerts_enabled BOOLEAN, 
        PRIMARY KEY (id), 
        UNIQUE (username), 
        UNIQUE (email)
)

2021-03-20 19:31:59,745 INFO sqlalchemy.engine.Engine [no key 0.00024s] ()
2021-03-20 19:31:59,761 INFO sqlalchemy.engine.Engine 
CREATE TABLE smtp (
        id INTEGER NOT NULL, 
        smtp_server VARCHAR(100) NOT NULL, 
        smtp_port INTEGER NOT NULL, 
        smtp_sender VARCHAR(100) NOT NULL, 
        PRIMARY KEY (id)
)

2021-03-20 19:31:59,761 INFO sqlalchemy.engine.Engine [no key 0.00027s] ()
2021-03-20 19:31:59,781 INFO sqlalchemy.engine.Engine 
CREATE TABLE hosts (
        id INTEGER NOT NULL, 
        ip_address VARCHAR(15) NOT NULL, 
        hostname VARCHAR(100), 
        status VARCHAR(10), 
        last_poll VARCHAR(20), 
        previous_status VARCHAR(10), 
        alerts_enabled BOOLEAN, 
        PRIMARY KEY (id), 
        UNIQUE (ip_address)
)

2021-03-20 19:31:59,781 INFO sqlalchemy.engine.Engine [no key 0.00020s] ()
2021-03-20 19:31:59,801 INFO sqlalchemy.engine.Engine 
CREATE TABLE polling (
        id INTEGER NOT NULL, 
        poll_interval INTEGER NOT NULL, 
        history_truncate_days INTEGER NOT NULL, 
        PRIMARY KEY (id)
)

2021-03-20 19:31:59,801 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2021-03-20 19:31:59,822 INFO sqlalchemy.engine.Engine 
CREATE TABLE web_themes (
        id INTEGER NOT NULL, 
        theme_name VARCHAR(100) NOT NULL, 
        theme_path VARCHAR(100) NOT NULL, 
        active BOOLEAN, 
        PRIMARY KEY (id)
)

2021-03-20 19:31:59,822 INFO sqlalchemy.engine.Engine [no key 0.00023s] ()
2021-03-20 19:31:59,841 INFO sqlalchemy.engine.Engine 
CREATE TABLE "pollHistory" (
        id INTEGER NOT NULL, 
        poll_time VARCHAR(20), 
        poll_status VARCHAR(20), 
        date_created DATE, 
        host_id INTEGER, 
        PRIMARY KEY (id), 
        FOREIGN KEY(host_id) REFERENCES hosts (id)
)

2021-03-20 19:31:59,842 INFO sqlalchemy.engine.Engine [no key 0.00021s] ()
2021-03-20 19:31:59,862 INFO sqlalchemy.engine.Engine 
CREATE TABLE "hostAlerts" (
        id INTEGER NOT NULL, 
        hostname VARCHAR(100), 
        ip_address VARCHAR(15), 
        host_status VARCHAR(20), 
        poll_time VARCHAR(20), 
        alert_cleared BOOLEAN, 
        date_created DATE, 
        host_id INTEGER, 
        PRIMARY KEY (id), 
        FOREIGN KEY(host_id) REFERENCES hosts (id)
)

2021-03-20 19:31:59,862 INFO sqlalchemy.engine.Engine [no key 0.00020s] ()
2021-03-20 19:31:59,882 INFO sqlalchemy.engine.Engine COMMIT
[2021-03-20 19:32:00,411] ERROR in app: Exception on /setup [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ipmon/ipmon/setup.py", line 82, in setup
    init_schedulers()
  File "/root/ipmon/ipmon/main.py", line 136, in init_schedulers
    update_poll_scheduler(int(json.loads(get_polling_config())['poll_interval']))
TypeError: list indices must be integers, not str
10.23.159.115 - - [20/Mar/2021 19:32:00] "POST /setup HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "/root/ipmon/ipmon/main.py", line 131, in handle_error
    return render_template('error.html', code=code, desc=desc)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 379, in _user_context_processor
    return dict(current_user=_get_user())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 331, in _load_user
    user = self._load_user_from_request(request)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 390, in _load_user_from_request
    user = self._request_callback(request)
  File "/root/ipmon/ipmon/auth.py", line 196, in request_loader
    if not verify_password(username, password):
  File "/root/ipmon/ipmon/auth.py", line 233, in verify_password
    return sha256_crypt.verify(password, get_user(username)['password'])
TypeError: tuple indices must be integers, not str

**Comment by mistergates** [comment]
Can you post the following for me:
The values used in the configuration form (sub any sensitive data)
`python --version` output
`python -m pip freeze` output
